import { GoogleGenerativeAI } from "@google/generative-ai";

const PRIMARY_MODEL = "gemini-2.5-flash";
const FALLBACK_MODEL = "gemini-1.5-flash";

const AVAILABLE_COMPONENTS = [
  'DailyCheckin',
  'ScoreCards',
  'WearableInsights',
  'AssessmentCards',
  'SuggestedForYou',

  'PersonalizedInsights',
  'SupportBanner',
];

const SYSTEM_PROMPT = `
You are a Senior Generative UI Architect. Your goal is a COMPLETE structural overhaul of the Wellness Dashboard.

AVAILABLE COMPONENTS (MANDATORY): 
1. DailyCheckin (No internalLayout)
2. ScoreCards (Internal keys: ScoreTeal, ScoreBlue, ScoreCoral)
3. WearableInsights (Internal keys: Header, DeviceInfo, StepsTracker, VitalsRow, AITip)
4. AssessmentCards (Internal keys: PHQ2, GAD2, DASS21)
5. SuggestedForYou (No internalLayout)
6. PersonalizedInsights (Internal keys: Header, Insight1, Insight2, Insight3)
7. SupportBanner (No internalLayout)

CRITICAL RULES:
1. TOTAL INCLUSION: The "layout" array MUST contain exactly 7 objects. One for each component listed above.
2. VALID KEYS: You MUST use the exact "elementKey" names listed above. Using wrong keys will cause blank UI.
3. UNIQUE IDs: Every object in the "layout" array MUST have a unique "id".
4. NO SIMPLIFICATION: Do NOT hide components.
5. INTERNAL ARCHITECTURE: For ScoreCards, WearableInsights, AssessmentCards, and PersonalizedInsights, you MUST provide a detailed "internalLayout" array using the valid keys. Mix "span": 1 and "span": 2.
6. VISIBILITY: All components and internal elements must have "isVisible": true.

Output MUST be a valid JSON object following this exact skeleton:
{
  "layout": [
    { "id": "card-daily", "componentKey": "DailyCheckin", "gridSpan": 4, "isVisible": true, "order": 0, "internalLayout": null },
    { "id": "card-scores", "componentKey": "ScoreCards", "gridSpan": 4, "isVisible": true, "order": 1, "internalLayout": [ { "elementKey": "ScoreTeal", "isVisible": true, "order": 0, "span": 1 }, ... ] },
    { "id": "card-wearable", "componentKey": "WearableInsights", "gridSpan": 2, "isVisible": true, "order": 2, "internalLayout": [ { "elementKey": "Header", "isVisible": true, "order": 0, "span": 2 }, ... ] },
    { "id": "card-assessments", "componentKey": "AssessmentCards", "gridSpan": 2, "isVisible": true, "order": 3, "internalLayout": [ { "elementKey": "PHQ2", "isVisible": true, "order": 0, "span": 2 }, ... ] },
    { "id": "card-suggested", "componentKey": "SuggestedForYou", "gridSpan": 4, "isVisible": true, "order": 4, "internalLayout": null },
    { "id": "card-insights", "componentKey": "PersonalizedInsights", "gridSpan": 4, "isVisible": true, "order": 5, "internalLayout": [ { "elementKey": "Insight1", "isVisible": true, "order": 0, "span": 2 }, ... ] },
    { "id": "card-support", "componentKey": "SupportBanner", "gridSpan": 4, "isVisible": true, "order": 6, "internalLayout": null }
  ],
  "aiReasoning": "Full 7/7 component redesign with verified internal element keys."
}
`;

/**
 * Extract text safely from response
 */
function extractText(response) {
  if (typeof response.text === 'function') return response.text();

  const candidate = response.candidates?.[0];
  const part = candidate?.content?.parts?.[0];

  return part?.text || "";
}

/**
 * Safe JSON parse (prevents crashes)
 */
function safeParseJSON(text) {
  try {
    // 1. Try direct parse
    return JSON.parse(text);
  } catch (e) {
    console.warn("JSON parse failed, attempting cleanup...");

    // 2. Try to extract JSON between curly braces
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      try {
        return JSON.parse(jsonMatch[0]);
      } catch (innerErr) {
        // 3. Fallback: aggressive cleanup of common AI issues
        const cleaned = jsonMatch[0]
          .replace(/```json/g, "")
          .replace(/```/g, "")
          .trim();
        try {
          return JSON.parse(cleaned);
        } catch (finalErr) {
          throw new Error("AI returned unparseable JSON structure");
        }
      }
    }
    throw new Error("No JSON structure found in AI response");
  }
}

async function callModel(genAI, modelName, prompt) {
  const model = genAI.getGenerativeModel({ model: modelName });
  const result = await model.generateContent(prompt);
  const response = await result.response;
  const text = extractText(response);

  const parsed = safeParseJSON(text);

  // VALIDATION: Ensure AI didn't skip any components
  if (!parsed.layout || parsed.layout.length < 7) {
    console.warn("AI returned incomplete layout, triggering fallback...");
    throw new Error("Incomplete layout generated by AI");
  }

  return parsed;
}

export async function generateAILayout() {
  const apiKey = import.meta.env.VITE_GEMINI_API_KEY;

  if (!apiKey) {
    console.error("Vercel/Local Error: VITE_GEMINI_API_KEY is missing.");
    throw new Error("API Key not found. Please set VITE_GEMINI_API_KEY in Vercel settings.");
  }

  const genAI = new GoogleGenerativeAI(apiKey);

  const prompt = `${SYSTEM_PROMPT}

ACTION: Perform a full-scale structural redesign now. Ensure all components are visible and shuffled.

STRICT RULE:
Return ONLY valid JSON. No markdown, no explanation.`;

  try {
    return await callModel(genAI, PRIMARY_MODEL, prompt);
  } catch (err) {
    console.warn("Primary failed, switching to fallback...", err);

    try {
      return await callModel(genAI, FALLBACK_MODEL, prompt);
    } catch (fallbackErr) {
      console.error("All models failed:", fallbackErr);

      // ✅ graceful fallback (VERY IMPORTANT for UI apps)
      throw new Error("Generative AI could not produce a layout");
    }
  }
}